#include <RendererFoundation/RendererFoundationPCH.h>

WD_STATICLINK_LIBRARY(RendererFoundation)
{
  if (bReturn)
    return;

  WD_STATICLINK_REFERENCE(RendererFoundation_Basics);
  WD_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_CommandEncoder);
  WD_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_CommandEncoderState);
  WD_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_ComputeCommandEncoder);
  WD_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_RenderCommandEncoder);
  WD_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_Device);
  WD_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_DeviceCapabilities);
  WD_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_DeviceFactory);
  WD_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_Pass);
  WD_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_SwapChain);
  WD_STATICLINK_REFERENCE(RendererFoundation_Profiling_Implementation_Profiling);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Buffer);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ProxyTexture);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Query);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_RenderTargetSetup);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_RenderTargetView);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ResourceFormats);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ResourceView);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Texture);
  WD_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_UnorderedAccessView);
  WD_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_Shader);
  WD_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_ShaderByteCode);
  WD_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_VertexDeclaration);
  WD_STATICLINK_REFERENCE(RendererFoundation_State_Implementation_State);
}
