#include <RendererVulkan/RendererVulkanPCH.h>

WD_STATICLINK_LIBRARY(RendererVulkan)
{
  if (bReturn)
    return;

  WD_STATICLINK_REFERENCE(RendererVulkan_Context_Implementation_ContextVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_DeviceVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_SwapChainVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_BufferVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_FenceVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_QueryVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_RenderTargetViewVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_ResourceViewVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_TextureVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_UnorderedAccessViewVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_ShaderVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_VertexDeclarationVulkan);
  WD_STATICLINK_REFERENCE(RendererVulkan_State_Implementation_StateVulkan);
}
